title: Tools Browser english blog
description: A English tech blog for learning Web Development and Mobile Technology.
theme: minima

url: "https://soumitra88875.github.io"
baseurl: "/tools-browser-english-blog"

permalink: /:year/:month/:day/:title.html

markdown: kramdown
paginate: 1
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
